a = TuXiangYuChuLi('test.png');
clc;
findFeature(a);
a = TuXiangYuChuLi('test_1.png');
clc;
findFeature(a);
a = TuXiangYuChuLi('test_2.png');
clc;
findFeature(a);
a = TuXiangYuChuLi('test_3.png');
clc;
findFeature(a);
a = TuXiangYuChuLi('test_4.png');
clc;
findFeature(a);
a = TuXiangYuChuLi('test_5.png');
clc;
findFeature(a);
a = TuXiangYuChuLi('test_6.png');
clc;
findFeature(a);
a = TuXiangYuChuLi('test_7.png');
clc;
findFeature(a);